### PR TITLE
Fix Vert.x PG PEM trust option configuration

### LINKED ISSUE #985: micronaut-jpa-reactive ssl connect cockroachdb error
## Micronaut 3.9.2 + jpa + reactive +vert.x +cockroachdb

1. my  yml vert.x config 
````
   vertx:
  pg:
    client:
      port: 26257
      host: 'coarse-gosling-2563.g95.cockroachlabs.cloud'
      database: 'defaultdb'
      user: 'bbbang'
      password: "tKEYTzKI8krk0_wys_uSpg"
      url: jdbc:postgresql://coarse-gosling-2563.g95.cockroachlabs.cloud:26257/db2?verify_full
      maxSize: 5
      ssl: true 
````
2. connect cockroachdb
 GET error   Trust options must be specified under verify-full or verify-ca sslmode

````

Caused by: java.lang.IllegalArgumentException: Trust options must be specified under verify-full or verify-ca sslmode
	at io.vertx.pgclient.impl.PgConnectionFactory.initializeConfiguration(PgConnectionFactory.java:69)
	at io.vertx.sqlclient.impl.ConnectionFactoryBase.<init>(ConnectionFactoryBase.java:81)
	at io.vertx.pgclient.impl.PgConnectionFactory.<init>(PgConnectionFactory.java:50)
	at io.vertx.pgclient.spi.PgDriver.createConnectionFactory(PgDriver.java:72)
	at io.vertx.pgclient.spi.PgDriver.lambda$newPoolImpl$1(PgDriver.java:51)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.vertx.pgclient.spi.PgDriver.newPoolImpl(PgDriver.java:51)
	at io.vertx.pgclient.spi.PgDriver.newPool(PgDriver.java:38)
	at io.vertx.pgclient.spi.PgDriver.newPool(PgDriver.java:25)
	at io.vertx.sqlclient.spi.Driver.createPool(Driver.java:70)
	at io.micronaut.configuration.vertx.pg.client.PgDriverFactory.build(PgDriverFactory.java:67)
	at io.micronaut.configuration.vertx.pg.client.$PgDriverFactory$Build0$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	... 69 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:54035', transport: 'socket'

````

throw exception  code:
````ignorelang

    switch (sslMode) {
      case VERIFY_FULL:
        String hostnameVerificationAlgorithm = options.getHostnameVerificationAlgorithm();
        if (hostnameVerificationAlgorithm == null || hostnameVerificationAlgorithm.isEmpty()) {
          throw new IllegalArgumentException("Host verification algorithm must be specified under verify-full sslmode");
        }
      case VERIFY_CA:
        TrustOptions trustOptions = options.getTrustOptions();
        if (trustOptions == null) {//ERROR this CODE
          throw new IllegalArgumentException("Trust options must be specified under verify-full or verify-ca sslmode");
        }
        break;
    }
    
````

how can id config trustOptions ?look like this ? trust-options/pem-trust-options
i hava the root ca file: certs/ca.crt 

````ignorelang
vertx:
  pg:
    client:
      port: 26257
      host: 'coarse-gosling-2563.g95.cockroachlabs.cloud'
      database: 'defaultdb'
      user: 'bbbang'
      password: "tKEYTzKI8krk0_wys_uSpg"
      url: jdbc:postgresql://coarse-gosling-2563.g95.cockroachlabs.cloud:26257/db2?verify_full
      maxSize: 5
      ssl: true
      pem-trust-options:# ?
        ca-cert:
          path: D:/certs/root.crt
      trust-options:   # ?
        ca-cert:      #  ?
          path: D:/certs/root.crt

````

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

windows
jdk17

### Example Application

https://github.com/jiliapp/micronaut-jpa-reactive-cockroachdb-demo

### Version

3.9.2

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- add explicit PEM trust option binding for the Vert.x PostgreSQL client
- resolve effective PG SSL options before pool creation so CA trust config is preserved
- document the configuration path and add focused regression coverage

## Verification
- ./gradlew :micronaut-vertx-pg-client:test --tests 'io.micronaut.configuration.vertx.pg.client.PgClientConfigurationSpec'

Resolves #985

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot review

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-sql/pull/1910#pullrequestreview-4114578205)

File: vertx-pg-client/src/test/groovy/io/micronaut/configuration/vertx/pg/client/PgClientConfigurationSpec.groovy [hunk 1]
```diff
@@ -48,6 +54,71 @@ class PgClientConfigurationSpec extends Specification {
         applicationContext?.stop()
     }
 
+    void "test vertx-pg-client connects with direct options when verify-ca trust options are configured"() {
```
Comment (radovanradic) [inline vertx-pg-client/src/test/groovy/io/micronaut/configuration/vertx/pg/client/PgClientConfigurationSpec.groovy:77]: Would it make more sense to do actual verification for pem trust options, something like 
```
void "test vertx-pg-client connects with direct options when verify-ca trust options are configured"() {
        given:
        int port = findFreePort()
        when:
        ApplicationContext applicationContext = ApplicationContext.run(
                'vertx.pg.client.host': 'localhost',
                'vertx.pg.client.port': port,
                'vertx.pg.client.ssl': true,
                'vertx.pg.client.ssl-mode': 'VERIFY_CA',
                'vertx.pg.client.pem-trust-options.cert-paths[0]': 'certs/ca.crt'
        )
        PgConnectOptions options = PgConnectOptionsResolver.resolve(
                applicationContext.getBean(PgClientConfiguration),
                applicationContext.getBean(PgPemTrustOptionsConfiguration)
        )
        PemTrustOptions trustOptions = (PemTrustOptions) options.sslOptions.trustOptions

        then:
        options.host == 'localhost'
        options.port == port
        options.sslMode == SslMode.VERIFY_CA
        options.sslOptions != null
        trustOptions.certPaths == ['certs/ca.crt']

        cleanup:
        applicationContext?.stop()
    }
```
And the other test as well
```
void "test vertx-pg-client uri mode keeps verify-ca trust options during connect"() {
        given:
        int port = findFreePort()

        when:
        ApplicationContext applicationContext = ApplicationContext.run(
                'vertx.pg.client.uri': "postgresql://user:secret@localhost:${port}/the-db",
                'vertx.pg.client.ssl': true,
                'vertx.pg.client.ssl-mode': 'VERIFY_CA',
                'vertx.pg.client.pem-trust-options.cert-paths[0]': 'certs/ca.crt'
        )
        PgConnectOptions options = PgConnectOptionsResolver.resolve(
                applicationContext.getBean(PgClientConfiguration),
                applicationContext.getBean(PgPemTrustOptionsConfiguration)
        )
        PemTrustOptions trustOptions = (PemTrustOptions) options.sslOptions.trustOptions

        then:
        options.host == 'localhost'
        options.port == port
        options.database == 'the-db'
        options.user == 'user'
        options.password == 'secret'
        options.sslMode == SslMode.VERIFY_CA
        options.sslOptions != null
        trustOptions.certPaths == ['certs/ca.crt']

        cleanup:
        applicationContext?.stop()
    }
```

which seems to fail as ssl options are not being set properly (which is issue probably existed before this PR)

File: vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgPemTrustOptionsConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * Configuration for PostgreSQL PEM trust options.
+ * <p>
+ * This configuration maps the {@code vertx.pg.client.pem-trust-options} namespace and allows
+ * specifying certificate files that should be trusted for SSL connections.
+ *
+ * @since 6.7.0
```
Comment (radovanradic) [inline vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgPemTrustOptionsConfiguration.java]:
```suggestion
 * @since 7.0.0
```

**Comment by graemerocher** [comment]
@copilot resolve the merge conflicts in this pull request

File: vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgConnectOptionsResolver.java [hunk 3]
```diff
@@ -0,0 +1,88 @@
+/*
+ * Copyright 2017-2020 original authors
```
Comment (radovanradic) [inline vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgConnectOptionsResolver.java]:
```suggestion
 * Copyright 2017-2026 original authors
```

File: vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgPemTrustOptionsConfiguration.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
+/*
+ * Copyright 2017-2020 original authors
```
Comment (radovanradic) [inline vertx-pg-client/src/main/java/io/micronaut/configuration/vertx/pg/client/PgPemTrustOptionsConfiguration.java]:
```suggestion
 * Copyright 2017-2026 original authors
```

**Review by radovanradic — APPROVED** [review]
